version: 2.1
jobs:
  "Classic":
    docker:
      - image: "cimg/base:2022.03"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: |
            sudo apt-get update
      - run:
          name: Install deps
          command: |
            sudo apt-get install -y build-essential
      - run:
          name: Check versions
          command: |
            cmake --version
      - run:
          name: Build
          command: |
            export CC=$(which clang)
            export CXX=$(which clang++)
            export CCACHE_DISABLE=1
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j 4 fift
      - run:
          name: Show OS info
          command: |
            uname -a
workflows:
  build:
    jobs:
      - "Classic"