version: 2.1
jobs:
  "Classic":
    docker:
      - image: "cimg/base:2022.03"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'sudo apt-get update && sudo apt-get install -y && sudo rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install deps
          command: |
            sudo apt-get update && apt-get install -y build-essential 
            sudo apt-get update && apt-get install -y git 
            sudo apt-get update && apt-get install -y make 
            sudo apt-get update && apt-get install -y cmake 
            sudo apt-get update && apt-get install -y clang 
            sudo apt-get update && apt-get install -y libgflags-dev 
            sudo apt-get update && apt-get install -y zlib1g-dev 
            sudo apt-get update && apt-get install -y libssl-dev 
            sudo apt-get update && apt-get install -y libreadline-dev 
            sudo apt-get update && apt-get install -y libmicrohttpd-dev 
            sudo apt-get update && apt-get install -y pkg-config 
            sudo apt-get update && apt-get install -y libgsl-dev 
            sudo apt-get update && apt-get install -y python3 
            sudo apt-get update && apt-get install -y python3-dev 
            sudo apt-get update && apt-get install -y python3-pip
      - run:
          name: Check versions
          command: |
            cmake --version
      - run:
          name: Build
          command: |
            export CC=$(which clang)
            export CXX=$(which clang++)
            export CCACHE_DISABLE=1
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j 4 fift
      - run:
          name: Show OS info
          command: |
            uname -a
workflows:
  build:
    jobs:
      - "Classic"