name: MacOS-15 TON build (shared, arm64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Create ~/.ccache
        run: |
          mkdir -p ~/.ccache

      - name: Cache TON test
        id: cache-ton
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ runner.arch }}-15-shared-ccache

      - name: Build TON
        run: |
          git submodule sync --recursive
          git submodule update
          cp assembly/native/build-macos-shared.sh .
          chmod +x build-macos-shared.sh
          ./build-macos-shared.sh -t -c
          ccache -s

      - name: Run Tests
        run: |
          cd build        
          ctest --output-on-failure --timeout 1800
