name: Create deb packages

on: [workflow_dispatch]

permissions: write-all

jobs:
  create-release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Get latest linux arm64 and amd64 artifacts
        run: |
          curl -L https://github.com/ton-blockchain/ton/releases/latest/download/ton-linux-arm64.zip -o ton-linux-arm64.zip
          curl -L https://github.com/ton-blockchain/ton/releases/latest/download/ton-linux-x86_64.zip -o ton-linux-amd64.zip
          unzip ton-linux-arm64.zip -d ton-linux-arm64
          unzip ton-linux-amd64.zip -d ton-linux-amd64

      - name: Build deb packages
        run: |
          mkdir -p ton-linux-deb-arm64/bin
          mkdir -p ton-linux-deb-arm64/lib
          cp ton-linux-arm64/* ton-linux-deb-arm64/bin/
          mv ton-linux-deb-arm64/bin/libtonlibjson.so.0.5 ton-linux-deb-arm64/lib/
            
          mkdir -p ton-linux-deb-amd64/bin
          mkdir -p ton-linux-deb-amd64/lib
          cp ton-linux-amd64/* ton-linux-deb-amd64/bin/
          mv ton-linux-deb-amd64/bin/libtonlibjson.so.0.5 ton-linux-deb-amd64/lib/
          
          # get latest tag
          TAG=$(git describe --tags)
          
          cd packages-out
          ./packages/deb.sh packages-out $PWD/packages/deb/ton $PWD/ton-linux-deb-amd64 amd64 ${TAG:1}
          ./packages/deb.sh packages-out $PWD/packages/deb/ton $PWD/ton-linux-deb-arm64 arm64 ${TAG:1}
          cd packages-out/deb-install
          dpkg-scanpackages -a amd64 . > Packages
          dpkg-scanpackages -a arm64 . >> Packages
          apt-ftparchive release . > Release
          
          gh release upload --clobber $TAG Packages Release ton_amd64.deb ton_arm64.deb 
