name: Windows TON build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

defaults:
  run:
    shell: cmd

jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check out current repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Craete directories
        run: |
          mkdir third_libs

      - name: Cache 3pp
        id: cache-3pp
        uses: actions/cache@v4
        with:
          path: third_libs
          key: ${{ runner.os }}-${{ runner.arch }}-windows-2019-3pp

      - name: Build TON
        run: |
          git submodule sync --recursive
          git submodule update
          copy assembly\native\build-windows-github-2019.bat .
          copy assembly\native\build-windows-2019.bat .
          build-windows-github-2019.bat Enterprise

      - name: Run Tests
        run: |
          cd build
          ctest -C Release --output-on-failure -E "test-bigint" --timeout 1800

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-x86-64-windows
          path: artifacts
